spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/valuetogether
    username: sa
    password:
    driver-class-name: org.h2.Driver

#  datasource:
#    url: jdbc:mysql://localhost:3306/valuetogether?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace