spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/valuetogether
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
<<<<<<< HEAD
      ddl-auto: none
=======
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL57Dialect
      dialect.storage_engine: innodb
>>>>>>> fad8618e2f2bbbef1332201b59d2fe7a5968f030
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true

#  datasource:
#    url: jdbc:mysql://valuetogether-db.c1ssbxrjps9r.ap-northeast-2.rds.amazonaws.com:3306/valuetogether
#    username: valuetogether
#    password: valuetogether
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: none
#      dialect: org.hibernate.dialect.MySQL57Dialect
#      dialect.storage_engine: innodb
#    properties:
#      hibernate:
##        show_sql: true
#        format_sql: true

  profiles:
    include: aws

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace