name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    # 1) 워크플로우 실행 전 기본적으로 체크아웃 필요
    - uses: actions/checkout@v3
    
    # 2) JDK 11 설치
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    # 3) gradlew 권한 설정
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
        
    # 4) Build Gradle
    - name: Build with Gradle
      uses: ./gradlew clean build
